language: go

go:
- "1.16.x"
- "tip"

services:
- postgresql

before_script:
- psql -c 'create database pg_dba_test;' -U postgres
- cat test-schema.sql | psql -U postgres > /dev/null

env:
  global:
  - GO111MODULE=on
  - POSTGES_DB=pg_dba_test
  - POSTGES_HOST=postgres
  - POSTGRES_USER=postgres

install:
- go install github.com/wadey/gocovmerge
- go get ./...

# Don't email me the results of the test runs.
notifications:
  email: false

script:
- go build ./cmd/pg-dba/...
- make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
